env:
  global:
    - CC_TEST_REPORTER_ID=bfe49936c2eff76912dd871c979208daf9ffa282cb5fde1812427bb99d6c683c
  
services:
  - docker

before_install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - make

script:
  - make tests

after_script:
  - sed -i "s@/var/www/webapp@$PWD@" clover.xml
  - ./cc-test-reporter after-build -t clover --exit-code $TRAVIS_TEST_RESULT

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0144b4a4eed4b62f881b
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
