env:
  global:
    - CC_TEST_REPORTER_ID=bfe49936c2eff76912dd871c979208daf9ffa282cb5fde1812427bb99d6c683c
  
services:
  - docker

before_install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - make

script:
  - make tests

after_script:
  - ./cc-test-reporter after-build tests/clover-coverage-report.xml -t clover -exit-code $TRAVIS_TEST_RESULT
