version: '3'

services:

  react:
    container_name: rmap-react
    image: quay.io/reconmap/web-client:master
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3001:3001
    environment:
      MYSQL_ROOT_PASSWORD: reconmuppet
      MYSQL_DATABASE: reconmap
      MYSQL_USER: reconmapper
      MYSQL_PASSWORD: reconmapped

