version: '3.8'

services:
    db:
        image: mysql:8.0
        volumes:
            - db_data:/var/lib/mysql
        restart: unless-stopped
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: reconmuppet
            MYSQL_DATABASE: reconmap
            MYSQL_USER: reconmapper
            MYSQL_PASSWORD: reconmapped
    fe:
        build:
            context: docker/frontend
            dockerfile: Dockerfile
        volumes:
            - "$PWD:/var/www/webapp"
        ports:
            - 8080:80

volumes:
    db_data:

