version: '3.8'

services:

  redis:
    container_name: rmap-redis
    image: redis:6.0
    command: redis-server --requirepass REconDIS
    ports:
      - 6379:6379
    volumes:
      - ./data-redis:/data

  mysql:
    container_name: rmap-mysql
    image: mysql:8.0
    volumes:
      - ./data-mysql:/var/lib/mysql
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: reconmuppet
      MYSQL_DATABASE: reconmap
      MYSQL_USER: reconmapper
      MYSQL_PASSWORD: reconmapped

  api:
    container_name: rmap-api
    build:
      context: docker/api
      dockerfile: Dockerfile
    volumes:
      - "$PWD:/var/www/webapp"
    ports:
      - 8080:80
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_USER: default
      REDIS_PASSWORD: REconDIS

  wss:
    container_name: rmap-wss
    image: quay.io/reconmap/ws-server:latest
    ports:
      - 8765:8765
    environment:
      VALID_ORIGINS: http://localhost:3001
      REDIS_HOST: redis://redis
      REDIS_PASSWORD: REconDIS

