openapi: 3.0.1

info:
  version: 0.1.0
  title: Reconmap API

servers:
  - url: 'http://localhost:3000'
  - url: 'https://api.reconmap.org'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      required: 
        - name
        - password
        - email
        - role
      properties:
        id:
          type: integer
        name:
          type: string
        password:
          type: string
        email:
          type: string
        role:
          type: string
    Target:
      type: object
      required:
        - projectId
        - name
        - kind
      properties:
        id:
          type: integer
        projectId:
          type: integer
        name:
          type: string
        kind:
          type: string

security:
  - BearerAuth: []
paths:
  /users/login:
    post:
      tags:
        - Users
      security: []
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '200':
          description: Succesful login response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
        '403':
          description: Unsuccesful login response
  /users:
    get:
      tags:
        - Users
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Succesful login response
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  password:
                    type: string
    post:
      tags:
        - Users
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: User succesfully created response
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  password:
                    type: string
  '/users/{id}':
    get:
      tags:
        - Users
      parameters:
        - name: id
          in: path
          description: User ID
          required: true
          schema:
            type: integer
            format: int64
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Succesful login response
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  password:
                    type: string

  /targets:
    post:
      tags:
        - Targets
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Target'
      responses:
        '200':
          description: User succesfully created response
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  password:
                    type: string
  '/targets/{id}':
    get:
      tags:
        - Targets
      parameters:
        - name: id
          in: path
          description: Target ID
          required: true
          schema:
            type: integer
            format: int64
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Succesfully retrieved
    delete:
      tags:
        - Targets
      parameters:
        - name: id
          in: path
          description: Target ID
          required: true
          schema:
            type: integer
            format: int64
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Succesfully deleted
